version: '3.8'

services:
  backend:
    build:
      context: ./
    # command: python manage.py runserver 0.0.0.0:8000 #gunicorn KorScrap.wsgi --bind 0.0.0.0:8000
    volumes:
      - static:/static
    ports:
      - 8000:8000
    env_file:
      - ./.env
  nginx:
    build: ./nginx
    volumes:
      - static:/static
    ports:
      - 80:80
    depends_on:
      - backend
volumes:
  static:
