# Generated by Django 4.0.2 on 2022-02-09 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fedor',
            fields=[
                ('productUrl', models.CharField(max_length=500, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('imgUrl', models.CharField(blank=True, max_length=500, null=True)),
                ('description', models.TextField()),
                ('price', models.FloatField()),
                ('brand', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
