# Generated by Django 4.0.2 on 2022-02-09 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('newsId', models.IntegerField()),
                ('tmb', models.ImageField(upload_to='tmbs')),
                ('title', models.CharField(max_length=255)),
                ('excerpt', models.CharField(max_length=255)),
                ('href', models.CharField(max_length=255)),
                ('count', models.CharField(max_length=255)),
                ('rcm', models.CharField(max_length=255)),
            ],
        ),
    ]
