# Generated by Django 4.0.2 on 2022-02-10 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_news_postdate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='id',
        ),
        migrations.AlterField(
            model_name='news',
            name='newsId',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
