# Generated by Django 4.0.2 on 2022-02-11 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0003_remove_news_id_alter_news_newsid'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='html',
            field=models.TextField(blank=True, null=True),
        ),
    ]
