# Generated by Django 4.0.2 on 2022-02-20 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0006_archives'),
    ]

    operations = [
        migrations.AddField(
            model_name='archives',
            name='link',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
