# Generated by Django 4.0.2 on 2022-02-22 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0007_archives_link'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='news',
            index=models.Index(fields=['-postDate'], name='content_new_postDat_252dba_idx'),
        ),
    ]
